export enum ADMIN_LIST_COLUMNS_VALUES {
  YEAR = "year",
  SEMESTER_NUMBER = "semesterNumber",
  CREATED_AT = "createdAt",
  ACTIONS = "actions"
}

export const ADMIN_LIST_COLUMNS = [
  ADMIN_LIST_COLUMNS_VALUES.YEAR,
  ADMIN_LIST_COLUMNS_VALUES.SEMESTER_NUMBER,
  ADMIN_LIST_COLUMNS_VALUES.CREATED_AT,
  ADMIN_LIST_COLUMNS_VALUES.ACTIONS
];
